# Generated by Django 3.2.16 on 2023-10-14 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_location'),
        ('blog', '0004_auto_20230519_0958'),
    ]

    operations = [
    ]
